### ISSUE TITLE
Way to temporary disable keyboard shortcuts

### ISSUE THREAD

**Issue by paulgreg** [shower/shower#166]
I’m working on a slide with an input which, on each keystroke, generates a SHA1 hash of its value.
When typing some keys in that input (like j/k, start/end or arrows key), shower goes to next/previous slides, which is expected.

I would like a way to temporary disable keys event by calling an API like shower.disableKeys() and shower.enableKeys() in my input’s focus/blur events.

**Comment by shvaikalesh** [comment]
Latest `@shower/code` correctly detects interactive elements (even custom ones, if they are focusable).
