### ISSUE TITLE
Append slide title to document title

### ISSUE THREAD

**Issue by h4** [shower/shower#185]
It will be made browser navigation better. I think, this screenshot explains my idea.

![shower-back](https://cloud.githubusercontent.com/assets/430023/2560902/b8d84a46-b7eb-11e3-9146-026a19d26d70.gif)

**Comment by pepelsbey** [comment]
Fixed in 2.0

![image](https://cloud.githubusercontent.com/assets/105274/13563063/a059006a-e43e-11e5-8f53-5a7acc7a3b00.png)
