### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by rauschma** [shower/shower#187]
It would be nice to be able to export to PDF (for Speakerdeck.com etc.). Maybe Shower can use the same approach as Reveal.js: https://github.com/hakimel/reveal.js#pdf-export

**Comment by HamsterCoder** [comment]
Hi, link to wiki is broken unfortunately. 
I think it  will be useful to have a hint in Readme. And maybe a Q/A on StackOverflow.

**Comment by pepelsbey** [comment]
@HamsterCoder, there’s work in progress on documentation at the moment, see [printing docs](https://github.com/shower/ribbon/blob/master/docs/printing-en.md), also available [in Russian](https://github.com/shower/ribbon/blob/master/docs/printing-ru.md) as well as WIP [features docs](https://github.com/shower/ribbon/blob/master/docs/features-ru.md).

**Comment by HamsterCoder** [comment]
Thanks I managed to get my way around browsing old issues. Great tool!

**Comment by iamchetanp** [comment]
Is there anyway to create link/button that download presentation automatically as PDF? So we can share link like Download Presentation.

**Comment by pepelsbey** [comment]
The easiest way would be to export your presentation to PDF and put it next to your `index.html`. Then you can make “Download Presentation” button (link) that would point to `index.pdf`. See PDF instructions on how to make PDF, it’s a easy as printing your slides from Chrome, but personally I prefer CLI way, it’s just faster.
