### ISSUE TITLE
Bad scrolling speed with inertia

### ISSUE THREAD

**Issue by operatino** [shower/shower#190]
On mac, with trackpad or magic mouse inertial scroll is enabled by default http://d.pr/i/ZB3y. Scrolling presentation with inertial scroll, slides are changed way too fast. And sometimes, when you try to scroll slowly, slides could suddenly play in reversed direction, which is very annoying.

To fix this problem, you must add a pause between scroll ticks, to stop unwanted slide skipping.

**Comment by shvaikalesh** [comment]
Closing because scrolling with `wheel` was removed for some time now.
