### ISSUE TITLE
D3js click and mouse events not working

### ISSUE THREAD

**Issue by RacingTadpole** [shower/shower#192]
Shower looks fantastic, and I'd love to use it to present some [d3](http://d3js.org) svg visualizations.  However, the d3 mouse and click events are not firing when embedded in shower; eg. I have just pasted the example code from the [Collapsible Force diagram](http://bl.ocks.org/mbostock/1062288) into a `<section>` in `index.html`. At that link, you can drag nodes around; inside shower, this is not possible.  Any ideas? Even a workaround would help.  Thanks!

**Comment by bclinkinbeard** [comment]
FWIW, this appears to have been (mostly?) fixed at some point. The dragging is a little weird in the collapsible force example cited above, but normal mouse overs and clicks seem to work fine.

This issue made me skeptical I could use Shower for my use case so I'm glad I checked for myself.

**Comment by shvaikalesh** [comment]
I can confirm that with mouse & latest `@shower/core`, copy-pasted [d3 example](https://bl.ocks.org/mbostock/raw/1062288) works in Shower just as good. Regarding touch actions: they are currently removed, but will be reimplemented with careful consideration of interactive elements.
