### ISSUE TITLE
Implement Background Images

### ISSUE THREAD

**Issue by una** [shower/shower#204]
Background images are relatively common -- this should be a data-attribute of some sort :)

**Comment by pepelsbey** [comment]
@una, have you tried `cover` slide type? It acts like background image (image goes under the slide content) and it’s much easier to apply it using `<img>` instead of background or some data attributes.

Have you seen the [Ribbon theme documentation](https://github.com/shower/shower/wiki/Ribbon)?

**Comment by una** [comment]
Yep -- I am using this. It requires an image tag, but it would be more semantic to use `background-size: cover` and apply backgrounds directly to the slides themselves.

**Comment by pepelsbey** [comment]
I would disagree with your idea of semantics here. Picture on your slide is a content, not decoration or styling and it should be presented as an `<img>` content element, not decoration `background`.

**Comment by una** [comment]
hmm I suppose it depends on what the image is. Generally when I have full-bleed images with text on top they are more of a style element -- background decoration. I do see your point though.
