### ISSUE TITLE
Idea to active "next note" when current "next" has "shownote" style.  

### ISSUE THREAD

**Issue by Pofigizm** [shower/shower#208]
It was need for me to show note comment on defined step in current slide.
I extended function slide.next from https://github.com/shower/core/blob/master/shower.js#L168

    ...
    nextSteps = document.getElementById(slide.id).querySelectorAll('.next:not(.active)');
    // start of added
    if (nextSteps[0].classList.contains('shownote')) {
        var nextNote = document.getElementById(slide.id).querySelectorAll('.note.next:not(.active)');
        nextNote[0].classList.add('active');
        slide.innerComplete++;
    }
    // end of added
    nextSteps[0].classList.add('active');
    ...

Maybe it will help somebody.

**Comment by pepelsbey** [comment]
@Pofigizm, have you seen [dev](https://github.com/shower/core/tree/dev) branch with new Shower’s core? It’s not much easier to extend Shower’s functionality: most of the functions are now plugins, see [next](https://github.com/shower/next) plugin for example.

**Comment by Pofigizm** [comment]
Ok, I will lean dev branch and new plugin system when I prepare my presentation in next time. Thank you, for you comment.
