### ISSUE TITLE
Video object seems at odd with webkit...

### ISSUE THREAD

**Issue by iherman** [shower/shower#213]
I have the following slide:

```
    <section class="slide">
      <div>
        <div>
          <h2> Whatever title</h2>
          <figure style="text-align: center"> 
            <video controls width="55%">
              <source src="videos/JavaBook.ogv" type="video/ogg"> 
              <source src="videos/JavaBook.mp4" type="video/mp4"> 
              <source src="videos/JavaBook.webm" type="video/webm">
            </video> 
          </figure>
        </div>
      </div>
    </section>
```

This used to work on a previous version of shower, but it has problems on some browsers with shower version v1.0.6 (I guess this is the last version).

I have tested on three browsers (all the browsers are up to date):

* It works perfectly on Mozilla
* On Chrome the control line appears twice, one sligthly on top of the other. The control on the top reacts on the start button but nothing is seen on the screen; the static image for the video appears underneath with a control panel, but that one does not react on the push event
* On Safari it looks very much like Chrome but the control panel underneath *is* reacting on push events and then the video plays properly

Because Chrome and Safari share quite a number of commonalities, so I guess this is related.

I have no access to IE, so I do not know how IE behaves.

**Comment by pepelsbey** [comment]
Do you the rest of the code or link that I could check? This code sample gives me nothing to work with.

**Comment by iherman** [comment]
@pepelsbey I have uploaded a small presentation onto:

http://www.ivan-herman.net/Tests/shower/

The behaviour is actually erratic, but wrong on Chrome, and also has bugs with Mozilla (it seems that the theme I used originally did hide some errors).

* When starting up the slide show it is a bit random on whether the start of the video has an effect or not. If one goes back to list mode and back to slide mode again, or reloads, sometimes the control does not have an effect. Note that this does not happen in Mozilla, only in Chrome
* In list mode the video appears twice. Once in the small representation of the slide and another time in elsewhere on the screen. I attach a screen dump below to show what I mean. Note that this happens both in Chrome and in Mozilla. 

What seems to be happening is that the video content is positioned twice. It may happen that, in slide mode, these two overlay, meaning that the control button may 'hide' one another. Or something like that... (Actually, I have experienced, in one other setting, still images being positioned twice, too, but I could not really put my finger on the problem, and I thought it was a CSS problem somewhere. Maybe it was a similar problem.)

I use one of the styles on github and not mine, to avoid accumulating errors.

I hope this helps finding the issue...


![screenshot](https://cloud.githubusercontent.com/assets/520723/8432134/7432bc6c-1f3e-11e5-929b-a131b1695500.png)

**Comment by pepelsbey** [comment]
Thank you, I’ll have a look

**Comment by pepelsbey** [comment]
Oh, I got it.

Please update your theme to the latest version. There was Live Region feature introduced in one of the last versions of Shower to make it more accessible, so there’s hidden element on every page which duplicates current slide content:
```
<section class="live-region" role="region" aria-live="assertive" aria-relevant="additions" aria-label="Slide Content: Auto-updating">
    </section>
```
Normally it’s `display:none` in list mode and offscreen in full one. So please update your theme to the latest version: here https://github.com/shower/ribbon or here https://www.npmjs.com/package/shower-ribbon

**Comment by iherman** [comment]
Thank you, @pepelsbey, this has indeed greatly improved this. But there is still a problem, albeit on Chrome only. The control panel (to start/stop the video) appears only when the window size is under a certain size. If I increase the size it disappears. This also means that, eg, if I run the slides, in Chrome, on full screen on my retina display of my Mac, there is not control panel.

This may be a chrome bug. As I said, this is on Chrome; the slides work properly on both Safari and Mozilla (I haven't got Opera running on my machine).

(I have updated the style sheet on my test site.)
