### ISSUE TITLE
Does shower 2.0 feature works?

### ISSUE THREAD

**Issue by s-stude** [shower/shower#214]
Hi,

Does wiki article for Shower 2.0 feature actual? Can I start using them?

https://github.com/shower/shower/wiki/Shower-2.0

**Comment by pepelsbey** [comment]
It was just a draft which we’ve used to create components for Shower 2.0, see [core:dev](https://github.com/shower/core/tree/dev) and [ribbon:next](https://github.com/shower/ribbon/tree/next) theme (both still in progress). Most of the mentioned features are implemented (open Ribbon theme in next branch to see yourself), but some are not yet there and nothing is properly documented yet.
