### ISSUE TITLE
Refresh is not working properly

### ISSUE THREAD

**Issue by CaledoniaProject** [shower/shower#217]
If you refresh from a hashed link, e.g xxxxx?full#2 

The page become empty and you need to press an arrow key to fix it, can you help?

**Comment by pepelsbey** [comment]
@CaledoniaProject, this is known issue caused by Chromium’s regression in `:target` selector support. See #211 for details. In short: it’s still an issue in stable Chrome 44 and Opera 30, but already fixed in Chrome Canary and Opera Developer based on Chrome 45+
