### ISSUE TITLE
HTML elements for slides & sectioning slides

### ISSUE THREAD

**Issue by RubenVerborgh** [shower/shower#219]
When comparing the HTML structure of Shower 1.0 and the upcoming Shower 2.0, I was happy to see that the double `<section class="slide"><div>` was replaced by a single `<section>` element, which is definitely a cleaner option.

However, I wonder whether `<section>` (without class) is the right element here, since a `<section>` might not be the correct logical type of unit. Concretely, many presentations are typically structured into 3 to 5 logical “sections”, each of which is preceded by an overview slide. An example structure could be:
- Title Slide
  - Overview slide with 3 topics (for introduction)
  - Overview slide with 3 topics, topic 1 highlighted
    - slides for topic 1
  - Overview slide with 3 topics, topic 2 highlighted
    - slides for topic 2
  - Overview slide with 3 topics, topic 3 highlighted
        - slides for topic 3
  - Overview slide with 3 topics (for summarization)

If I were to write one of the above parts in HTML, I would do:
```
<section>
  <h1>Topic 1</h1>
  <section class="slide overview">
    <h2>Overview</h2>
    (overview items)
  </section>
  <section class="slide">
    <h2>A slide for topic 1</h2>
    (slide content)
  </section>
   …
<section>
```

So `<section>` would be used for the logical sections (= few) of the presentation; `<section class="slide">` (or even `<div class="slide">`) for actual slides (= many).

The issue seems to be that, since version 2.0 uses `<section>` without any class, it would not be possible to group slides in such a way. And putting `<section>`s in a `<div>` would be strange.

**Is there any possibility to logically group slides?**

PS An interesting feature I was thinking about (not necessarily for core, but something I'd implement in a custom script myself) is the automated generation of overview slides, which would follow naturally from logical sectioning.

**Comment by pepelsbey** [comment]
You know, I actually agree with you.

The point of removing nested `<div>` wrapper was to make it easier to write slides, but I had to simplify some built-in themes functionality to achieve this (it’s not possible to move elements outside of the slide, including slide numbers).

The same applies to class names. It’s much easier to use `<section>` element without any class name when you hand-code your presentation. And it’s still true. But now it’s not possible to wrap slides into groups or modify markup any other way. There is very good use case for grouping slides: apparently it’s the only good way to start list numbering on one slide and proceed numbering on the other.

I think I know what I’m going to do: I’ll go back to `class="shower list"` on `<body>` (instead on BEM-inspired `shower__list`) and `<section class="slide">` to make it clear and more flexible.

So thank you for your questions. I’ll close this issue once all mentioned changes are implemented.

BTW, both Shower 1.x and 2.0 are flexible enough to specify your own selector for slides, [see example](https://github.com/shower/core/blob/dev/lib/shower/Shower.js#L58).

**Comment by RubenVerborgh** [comment]
This is very good to hear, and very happy about the custom selector possibility as well.

BTW The reason I chose Shower (and am somewhat picky about HTML elements) is that I'll use it for a series on Web fundamentals for our students at Ghent University—so I want to practice what I preach :smile: The fact that Shower is HTML and CSS-driven, with proper unobtrusive JavaScript, is a very good example. Add to that the very communicative slides (focusing on simplicity) and excellent typography… match made in heaven :wink:

**Comment by RubenVerborgh** [comment]
Oh and, I was actually going to ask about `shower__list` next, depending on your answer. Fully agree there as well.

**Comment by pepelsbey** [comment]
So, [slide code](https://github.com/shower/ribbon/blob/next/index.html#L15) for built-in themes is back to `slide` class name:
```
<section class="slide">
    …
</section>
```
And [slide’s styles](https://github.com/shower/ribbon/blob/next/styles/slide/slide.scss#L9) are attached to `slide` class name:
```
.slide {
	position:relative;
	z-index:1;
	overflow:hidden;
	padding:106px 100px 0;
	…
```
Core module in `shower/core:dev` is [updated accordingly](https://github.com/shower/core/commit/2123f90e0ec7ab60f4080fe2a7bb4097365b6b56).

**Comment by pepelsbey** [comment]
This approach and overall themes architecture should be considered as final for Shower 2.0 release.

Thank you again for opening this issue!

**Comment by RubenVerborgh** [comment]
Great, thanks a lot for this. That allows me to do exactly what I want, and it's a clean solution HTML-wise. I'll let you know when I have finished slide decks that use `section` to partition presentations.
