### ISSUE TITLE
Black screen after edit

### ISSUE THREAD

**Issue by sergeyzwezdin** [shower/shower#221]
I wonder what's typical scenario to edit slides? Once I edit HTML and press F5 in browser it just switch between list/full screen mode. Ok, I click "Reload" button from toolbar − it forces page to reload, but I see black screen until I switch next/prev slide. Not so productive to edit slides such way, does it? :-)

I guess there is another convenient way to edit slides − @pepelsbey could you share how you doing it?

P.S. Chrome 44

**Comment by pepelsbey** [comment]
@sergeyzwezdin, it’s a known Chromium bug, see #211 and #217 for details. Once you have Chrome 45 it will be fixed.

**Comment by sergeyzwezdin** [comment]
Ok, thanks.
