### ISSUE TITLE
History API doesn’t work for local files

### ISSUE THREAD

**Issue by ai** [shower/shower#222]
`History.pushState` is prohibited in local files. As result there is not way to open Shower presentation as file from disk.

@pepelsbey seems like critical issue.

**Comment by pepelsbey** [comment]
Yes, since Chrome 45 History API doesn’t work. We’re open to suggestions, something better than _“just use hashbangs alredy”_ :\

**Comment by ai** [comment]
Can tag has two IDs? `1` and `full1`?

**Comment by pepelsbey** [comment]
@ai, the point of real ID is to use `:target` pseudo-class for the current slide, which works even without JS. This is the right thing to do: use features available in the language exactly how they were designed.

**Comment by ai** [comment]
@pepelsbey I know, this is why I ask about two IDs.

**Comment by pepelsbey** [comment]
There’s only one ID in `index.html#full1`, non-exiting one :(

**Comment by ai** [comment]
What about removing ID changes in overview mode? Why we need to non-JS keyboard selection?

**Comment by pepelsbey** [comment]
Let’s look at the following URL: `index.html?full#last` — full mode, last slide, clean and simple. And if you remove `?full` you’ll get `index.html#last` last slide in list mode or without `#last` you’ll get `index.html?full` just a full screen mode with the very first selected.

This system is too good to just trash it.

**Comment by pepelsbey** [comment]
If you have `index.html#full-last` and `index.html#last` it could mean anything and this is not something you’d edit manually to change current slide or presentation’s mode :(

**Comment by ai** [comment]
@pepelsbey the bug is critical to denial ;).

`?full#last` was not so good solution, because query part of URL mean different thing. We have same document, so we need to have same URL without hash.

**Comment by ai** [comment]
@pepelsbey so what do you think if `index.html#last` will be a fullscreen slide and we week not have non-JS keyboard in overview.

We need to fix this issue as fast as possible, and non-JS keyboard overview is to rare case.

**Comment by pepelsbey** [comment]
@zloylos, any ideas how this could be fixed? This is rather critical as most presentations are launched locally and setting up a server is not a viable option in many cases :\

**Comment by pepelsbey** [comment]
I wonder if History API could polifilled somehow only for Chrome. There’s [history.js](https://github.com/browserstate/history.js/) for example.

**Comment by ai** [comment]
@pepelsbey it is common security issue. This bahviour will be standard way or we all will have secirity problems.

**Comment by pepelsbey** [comment]
Solution is to use only slide IDs `index.html#1` and store mode in body class name `<body class="shower full">` and in `localStorage` so it would if you reload page. And open in full screen mode by default if there’s `#ID` in URL and in the list mode if there’s no one.

**Comment by ai** [comment]
@pepelsbey who is current JS programmer to ask to fix it? I can also try to fix it, when I will finish slides.

**Comment by zloylos** [comment]
@pepelsbey @ai I will try to fix it for few days.

**Comment by pepelsbey** [comment]
Fixed by shower/core/pull/22

**Comment by pepelsbey** [comment]
Right, it seems they have reverted this behavior for local files. This thing works fine in the current Chrome.

```
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title></title>
</head>
<body>
	<script>
		history.replaceState(null, null, '?full');
	</script>
</body>
</html>
```

@shvaikalesh, I guess it’s time to bring it back :) But let me test in IE/Edge first.

**Comment by pepelsbey** [comment]
It works just fine in IE11 and Edge, as well as Firefox and Safari.
