### ISSUE TITLE
Refresh results in black screen

### ISSUE THREAD

**Issue by vmarkovtsev** [shower/shower#223]
When I change index.html and hit Ctrl - Shift - R, a see the black screen instead of current slide. I have to press <left> and then <right> to eventually show it.

**Comment by pepelsbey** [comment]
@vmarkovtsev, update you Chrome to the latest version (45 at least), I won’t happen again. See #211 for details.

**Comment by pepelsbey** [comment]
If it doesn’t help feel free to reopen this issue with additional details: browser, platform, etc.
