### ISSUE TITLE
Unable To Activate Slides

### ISSUE THREAD

**Issue by thebrownsquare** [shower/shower#226]
Hey, guys. I'm new to this and just downloaded the Bright-Master .zip file. Clicking on the slides in the index view does nothing, and I can't get anything into full-screen mode or actually give a presentation. Has something changed? What am i missing?

**Comment by pepelsbey** [comment]
@thebrownsquare, Bright is just a theme, you need a full package, including core (engine). See [Simple Way](https://github.com/shower/shower#using-shower) section in readme. If you’re ready for something more advanced, see [Shower: Create, Publish & Share](https://www.youtube.com/watch?v=l2OelK_hIro) screen cast.
