### ISSUE TITLE
Can we still link to fullscreen slides?

### ISSUE THREAD

**Issue by RubenVerborgh** [shower/shower#228]
I noticed that in the latest `next`, slides in overview and in fullscreen view both are addressed by `#37`. Does that mean we can no longer link to fullscreen slides? Can we indicate a preference to open fullscreen if a specific slide is linked?

**Comment by pepelsbey** [comment]
Currently it’s not possible to have the `full` state in URL, it could be triggered only for `<body class="shower full">` (in which case Shower will start in full screen by default) or by manually clicking a slide to enter full screen mode. It’s the case both in `next` (2.0) and `master` (1.2) core versions.

There’s an idea to have something like `index.html#37:full` (fake ID only for full screen mode), but it will happen only after 2.0 release (this Sunday).

**Comment by RubenVerborgh** [comment]
2.0 release coming this Sunday? Awesome :smile:

I remember there being `full` in the URL somewhere between `master` and `next`; however, I think `class="shower full"` is actually nicer. After all, it's just a different view of the same thing.

**Comment by pepelsbey** [comment]
@RubenVerborgh, yes, it used to be possible to link to a slide in full screen mode `index.html?full#37` but mode switching has stopped working in the latest Chrome (History API for `file://` protocol is not considered secure anymore) that’s why it’s disabled now.

**Comment by RubenVerborgh** [comment]
After working with the latest version now for a while, I find it unintuitive that removing the `#37` from `index.html#37` does not simply bring me back to the overview, as I would expect from entering the page the first time. I think the local storage thing does more bad than good; link behavior should be predictable, and not depend on a local setting somewhere, which cannot be altered easily. (In particular on mobile, how do I press escape?)

On the other hand, I do expect the view to stay the same when I refresh.

Suggestion: does it make sense to always show the overview when the hashless URL is used?

**Comment by RubenVerborgh** [comment]
Following up on this with shower/core#109.

**Comment by drdwitte** [comment]
I noticed that pressing 'Esc' brings back the overview. Can this event be triggered in a different way?
