### ISSUE TITLE
Mobile: can't next/prev with full-screen image

### ISSUE THREAD

**Issue by RubenVerborgh** [shower/shower#229]
With the latest `dev`, I can't go to the next or previous slide by tapping on the right or left bottom of the slide if the slide consists of a full-screen image (`<img class="cover">`). This works for other slides.

**Comment by zloylos** [comment]
Shower 2.0 in production. Bug fixed in shower-core 2.0.1.
Can you update dependences and check again?

**Comment by RubenVerborgh** [comment]
Perfect, thanks!
