### ISSUE TITLE
http://shwr.me/ is broken

### ISSUE THREAD

**Issue by RubenVerborgh** [shower/shower#230]
Slides 1 and 8 have display problems.

**Comment by xamgore** [comment]
As well as [ribbon](http://shwr.me/shower/themes/ribbon/) & [material](http://shwr.me/shower/themes/material/) themes — none of slides are clickable.

**Comment by pepelsbey** [comment]
Fixed, sorry about that.

http://shwr.me/
http://shwr.me/shower/themes/ribbon/
http://shwr.me/shower/themes/maretial/
