### ISSUE TITLE
Malware alert on Windows 8 when download from http://shwr.me/shower.zip

### ISSUE THREAD

**Issue by tytskiy** [shower/shower#232]
When download archive directly from http://shwr.me/shower.zip Windows 8 detects a malware inside of  archive and prevents from downloading.

In the same time i am able to download archive from https://github.com/shower/shower/archive/2.0.0.zip with no problem.
![2016-01-18_1545](https://cloud.githubusercontent.com/assets/2727037/12394234/e107dd9e-bdfa-11e5-82a7-76dc8333a441.png)

**Comment by pepelsbey** [comment]
@tytskiy, `shower.zip` is not equal to `2.0.0.zip` since it contains themes and core. Folder structure is also different, the one on `shwr.me` domain is more convenient. I’ll see what I can do to make this alert go away, but there’s definitely no malware there.

**Comment by pepelsbey** [comment]
Have submitted http://shwr.me/shower.zip for review to remove the warning.

**Comment by tytskiy** [comment]
@pepelsbey i tried this one, but ended with the same result. 
I also tried to save web-page http://shwr.me/#cover directly, using browser's feature `CTRL S`.
But once page it downloaded, file `shower.min.js` is deleted immediately, and and malware alert shown.

**Comment by tytskiy** [comment]
@pepelsbey i have another details about the issue
![1](https://cloud.githubusercontent.com/assets/2727037/12511385/40c3830a-c111-11e5-8f76-3ed30e35052d.png)

Description from MS: https://www.microsoft.com/security/portal/threat/Encyclopedia/Entry.aspx?Name=Trojan:Win32/Spursint.A

After short googling i found similar issues:

- https://github.com/google/material-design-lite/issues/1754
- https://github.com/google/material-design-lite/issues/1812

It seems like unsolvable. 
Then corporate workers are not able to use shower engine.

Could you please report the issue to Microsoft by yourself as you are the author of this software? 

And i think issue can be closed, if there is no possibility to fix it from your side.

**Comment by gorohoroh** [comment]
For the record, this also occurs on Windows 10 with Windows Defender on.

**Comment by pepelsbey** [comment]
@tytskiy, thank you for details, will try to fix it. This issue will remain open until it’s fixed.

**Comment by pepelsbey** [comment]
Whitelisting request is also submitted via [Malware Protection Center](https://www.microsoft.com/security/portal/developer/contactus.aspx)

**Comment by pepelsbey** [comment]
Fixed on Microsoft side thanks to Constantin Kichinsky. Could you please confirm?

![image](https://cloud.githubusercontent.com/assets/105274/13195355/048a3016-d7c1-11e5-90ea-4863cb86683b.png)

**Comment by tytskiy** [comment]
@pepelsbey i am able to fully confirm this on Monday 22.02.2016. 
On my home PC this works good now.

**Comment by tytskiy** [comment]
@pepelsbey it works! Thank you

**Comment by pepelsbey** [comment]
@tytskiy, thank you for the heads up!
