### ISSUE TITLE
Вирус в архиве

### ISSUE THREAD

**Issue by nicothin** [shower/shower#233]
Windows 10 64bit, штатное средство проверки при скачивании архива http://shwr.me/shower.zip (ссылка в readme) блокирует архив, утверждая, что там вирус.
При установке зависимостей по `npm i` — аналогично.
Сборка, соответственно, не срабатывает. (`Warning: Unable to read "node_modules/shower-core/shower.js" file (Error code: UNKNOWN).`)
Скрин журнала: http://take.ms/fZQMm

**Comment by pepelsbey** [comment]
Thanks for reporting this, but see #232
