### ISSUE TITLE
Full screen shouldn't be delayed until everything is loaded

### ISSUE THREAD

**Issue by RubenVerborgh** [shower/shower#249]
**Context**
- a presentation is opened and will automatically go into full screen mode<br>(i.e., full screen was set in local storage)

**Current behavior**
- Shower waits until everything is loaded (images, video, iframes, etc. on individual slides)<br>before going full screen

**Expected behavior**
- Shower goes full screen as soon as possible

For slides with a lot of content, this delay gets quite annoying.

**Comment by pepelsbey** [comment]
I just briefly tested it using network throttling and “disable cache” option in Chrome DevTools and got shwr.me page in full screen immediately. Here’s cover picture still progressively loading:

![image](https://cloud.githubusercontent.com/assets/105274/13571509/b785e7a8-e475-11e5-9008-9a9de39bdc08.png)

**Comment by RubenVerborgh** [comment]
Confirmed. Turns out Chrome is quite sensitive to the order of `iframe` and `script` tags.
