### ISSUE TITLE
Make the tests run again

### ISSUE THREAD

**Issue by RubenVerborgh** [shower/shower#253]
Currently, some tests fail on `master`. It would be great to fix those, so working on Shower becomes easier again.

I can volunteer to help out here, but I wanted to bring this up for discussion first.

**Comment by pepelsbey** [comment]
There are two ways of solving this problem:

1. Fix existing set of tests that is not complete (some pre-2.0 bits are still there) on the system (CasperJS) that is not reliable enough (that’s why some tests are failing) or…
2. Develop a new set of tests on a better system, probably [WebdriverIO](http://webdriver.io/)

But it could be not _or_, but _and_. My problem here is the lack of time and experience in proper functional testing.

**Comment by RubenVerborgh** [comment]
Alright, so the problem is not that the tests are broken, but that CasperJS was/is buggy?
It is my impression that the same tests are failing consistently, so maybe it's worth giving this option a shot.

**Comment by pepelsbey** [comment]
CasperJS was/is buggy, but some tests are incorrect too. Will try to have a look today.
