### ISSUE TITLE
# appended in Firefox once page is loaded

### ISSUE THREAD

**Issue by pepelsbey** [shower/shower#257]
Steps to reproduce:
1. Open [shwr.me](http://shwr.me/) in Firefox
2. Check page address

Expected: `http://shwr.me/`
Actual: `http://shwr.me/#`

The same applies to local files.

**Comment by binjospookie** [comment]
The simplest way to resolve this problem is using [cssua](http://cssuseragent.org). And if `<html>` contains class `ua-gecko` then remove `#`. What do you think about this solution?

**Comment by pepelsbey** [comment]
@binjospookie, I’d rather try to solve it, not hide. Let’s see what Mozilla think about it.

Any idea, @miketaylr?

**Comment by miketaylr** [comment]
Hrm, interesting. Gecko, Opera 12 (Presto) and Edge all do the same thing. 

It seems that setting `location.hash` to the empty string (in `_init` or shower.js) via `window.location.hash = ""` results in `#` being appending to the URL, except in WebKit and Blink.

I'm not intimately familiar with the URL standard's algorithms ([which are used in `location.hash`'s setter](https://html.spec.whatwg.org/multipage/browsers.html#dom-location-hash)), but maybe @annevk would know what the right behavior here is?

**Comment by annevk** [comment]
Currently we require empty string to result in # in the HTML standard.

**Comment by miketaylr** [comment]
Thanks @annevk. So @pepelsbey -- seems like this is actually a Chrome bug.
