### ISSUE TITLE
Printable to PDF - How to make it work

### ISSUE THREAD

**Issue by sureshn** [shower/shower#260]
I do not see any steps or document which explains how to Print the prepared slide deck into PDF
Can you some one please provide that info

**Comment by sureshn** [comment]
Note that if I use the print as pdf option, the slides in the PDF would have lost formatting and orientation
I have attached the presentation I am working on and you can see how the formatting is totally gone after doing a save as pdf 
[Fossil SCM - For the Enterprise.pdf](https://github.com/shower/shower/files/217767/Fossil.SCM.-.For.the.Enterprise.pdf)

**Comment by pepelsbey** [comment]
Here’s printing doc: [docs/printing-en.md](https://github.com/shower/shower/blob/master/docs/printing-en.md)

> You can export your presentation to PDF
> by sending it to print in list mode in **Chrome and Opera** desktop browsers.

It looks like you’ve printed it not in Chrome or Opera. The problem is that other browsers don’t support `@page` rule which allows to set page width and height.

**Comment by sureshn** [comment]
I printed it out from a safari browser  initially (from my mac), today I tried it out from a chrome browser and still the formatting and orientation does not stay ,

**Comment by pepelsbey** [comment]
Make sure you’re doing right, it step by step:

1. Open presentation in Chrome or Opera
2. Go to list mode
3. Go to print dialog
4. Select PDF as a target

And you’ll see this

![image](https://cloud.githubusercontent.com/assets/105274/14522160/e7e65b34-0235-11e6-89f3-908c38aeb2d4.png)

**Comment by sureshn** [comment]
Yeah, the list view finally did the trick for me, so the way the print works is to get into the list view with #cover suffixed to the end or the URL (or by default it should already be there) and then doing a print , all this only in chrome (would not work in safari ) , how ever using Chrome did unblock me and my presentation is ready to go now !
Many thanks for the prompt response !

**Comment by pepelsbey** [comment]
You’re welcome. We should probably detect printing and switch to list mode to make it easier.
