### ISSUE TITLE
Replace get…/_get… by property accessors

### ISSUE THREAD

**Issue by RubenVerborgh** [shower/shower#265]
In several places, the code uses the `get…` paradigm to obtain values. Using properties is more idiomatic in those cases for JavaScript. It can make the code easier and eliminate some code (sometimes, it is okay to just expose a variable; if not, a setter can be built without changing the syntax). This would bring some uniformity to the code as well, since sometimes member variables are used.

I can volunteer to make a PR.

**Comment by shvaikalesh** [comment]
Resolved in https://github.com/shower/core/pull/134.
