### ISSUE TITLE
Shower wiki disappeared

### ISSUE THREAD

**Issue by RubenVerborgh** [shower/shower#266]
The Shower wiki seems to have disappeared. https://github.com/shower/shower/wiki currenctly results in a redirect.

**Comment by pepelsbey** [comment]
There’s [docs section](https://github.com/shower/shower/tree/master/docs) in the main repository. Most of the docs are located there, some old ones from wiki are outdated but will be back once I finish clean up.

**Comment by RubenVerborgh** [comment]
Some of the subrepos still refer to the Wiki; perhaps this should be updated as well.

**Comment by pepelsbey** [comment]
Oh, I thought I fixed all links. Where have you seen them?

**Comment by RubenVerborgh** [comment]
https://github.com/shower/next

**Comment by pepelsbey** [comment]
Fixed. Thank you for heads up.
