### ISSUE TITLE
Fail to print shower slides on Safari but works fine on Chrome

### ISSUE THREAD

**Issue by luo820802** [shower/shower#277]
Will it be possible that Safari can output shower slides as pdf normally? I tries this on Chrome and the format stayed as it should be. But Safari was a mess...
Output of Safari 
![diffusion mri theory methods and applications-7 dragged](https://cloud.githubusercontent.com/assets/10905163/17477357/6efca4ae-5d97-11e6-8bd7-0abe55e2c610.png)
But it should look like this from Chrome
![diffusion mri theory methods and applications](https://cloud.githubusercontent.com/assets/10905163/17477405/b27d56ba-5d97-11e6-86aa-1521c549f315.png)

**Comment by pepelsbey** [comment]
See #143 and [printing docs](https://github.com/shower/shower/blob/master/docs/printing-en.md). In short: Safari doesn’t support needed technologies to print right from the browser.
