### ISSUE TITLE
Allow advancing via click of button

### ISSUE THREAD

**Issue by koen-serry** [shower/shower#283]

**Comment by koen-serry** [comment]
Hi,

since this is more a plugin than something of the core I embedded the code inline (since the code is pretty trivial). Maybe it's helpful to some people.

`
shower.modules.require(['shower'],function(a){a.plugins.add("shower-click")});
shower.modules.define("shower-click", [ 'util.extend'], function (provide,extend) {

    var _this;
    function Click (shower, options) {
        options = options || {};
        this._shower = shower;
        _this = this;
        this._setupListeners();
    }


    extend(Click.prototype,{
        destroy: function () {
            this._clearListeners();
            this._shower = null;
        },

        _setupListeners: function () {
            var shower = this._shower;
            // this._showerListeners = shower.events.group().on('add', this._onSlideAdd, this);
            this._shower.getSlides().forEach(this._addClickListener, this);
        },

        _clearListeners: function () {
            // this._showerListeners.offAll();
            this._shower.getSlides().forEach(this._removeClickListener, this);
        },

        _addClickListener: function (slide) {
            var element = slide.layout.getElement();
            element.addEventListener('click', this._onClick, false);
        },

        _removeClickListener: function (slide) {
            var element = slide.layout.getElement();
            element.removeEventListener('click', this._onClick, false);
        },

        _onClick: function (e) {
            var shower = _this._shower,
                player = _this._shower.player;
            if(player.getCurrentSlideIndex() == shower.getSlidesCount() - 1)
                player.first();
            else
                player.next();
        }
    });
    provide(Click);
})
`

**Comment by pepelsbey** [comment]
Hi Koen, it might be a good idea for an actual plugin. Shower distributive [consists of several of them](https://github.com/shower/core/blob/master/package.json#L62-L65), for example [shower-progress](https://github.com/shower/progress) or [shower-next](https://github.com/shower/next).

So if you’re interested enough you could make a real plugin of it and move it to [Shower GitHub organization](https://github.com/shower) if you want.

**Comment by shvaikalesh** [comment]
Simpler implementation for latest `@shower/core`:

```js
const [lastSlide] = shower.slides.slice(-1)
const handleClick = event => {
  if (event.defaultPrevented) return
  if (event.target.tabIndex != -1) return

  if (shower.isListMode) return
  if (shower.activeSlide == lastSlide) {
    shower.first()
  } else {
    shower.next()
  }
}

shower.slides.forEach(slide => {
  slide.element.addEventListener("click", handleClick)
})
```
