### ISSUE TITLE
page-break-after: always

### ISSUE THREAD

**Issue by mnot** [shower/shower#284]
Presentations are much easier to print with this CSS on `section`; Material (at least) lacks it.

**Comment by pepelsbey** [comment]
I have never actually printed any of my slides on paper so it's hard to tell :) I've always considered PDF as a print target and it works great in this case. Let me check if it doesn't break anything first and then I'll add it to both built-in themes.

**Comment by mnot** [comment]
Sorry - by "print" I meant "save as PDF" :)

It doesn't work so well in my case, e.g., for https://www.mnot.net/talks/web-adventure/

**Comment by pepelsbey** [comment]
Have you seen [printing documentation](https://github.com/shower/shower/blob/master/docs/printing-en.md)? It suggest using Chromium-based browsers for PDF export since `@page` options required for the page sizing are supported only in such browsers.

How do you print your slides to PDF?

**Comment by mnot** [comment]
Aha - I didn't see those docs (wasn't linked from wherever I looked), but I did try from Chrome; it was a mess. I think it's because I printed from the fullscreen view, not the list view (which works perfectly).

Thanks!

**Comment by pepelsbey** [comment]
I'll make sure that docs are visible from the readme. I should probably also detect printing somehow and switch mode to the list.

Anyway, I'm glad it worked for you. Thank you for using Shower :)
