### ISSUE TITLE
Timed presentations / advance automatically after delay

### ISSUE THREAD

**Issue by nekromoff** [shower/shower#285]
I would like to see an option to advance automatically after some delay. I don't see that mentioned in the features or in the examples. Is that possible?

**Comment by pepelsbey** [comment]
See [slide 28](https://shwr.me/shower/themes/ribbon/#28), it advances automatically in a few seconds because `data-timing` attribute is set.

**Comment by nekromoff** [comment]
Thumbs up!

**Comment by shvaikalesh** [comment]
As of new `@shower/core`, `data-timing` could have either `3s` or `00:03` format.
