### ISSUE TITLE
Screen.css 404

### ISSUE THREAD

**Issue by binjospookie** [shower/shower#286]
There are 3 presentations from README, which include this error:

* [Возвращение ножа и паровоза](https://pepelsbey.net/pres/knife-train/)
* [-Пре-фиксы. Зачем и как правильно](https://pepelsbey.net/pres/pre-fixes)
* [Вёрстка со смыслом](https://pepelsbey.net/pres/sense-coding/)

Error message: 
```
Failed to load resource: the server responded with a status of 404 ()
https://pepelsbey.net/pres/shower/themes/ribbon/styles/screen.css
```

It's not a great error, but...

**Comment by pepelsbey** [comment]
Fixed by upgrading presentations to newer versions. Thank you!
