### ISSUE TITLE
Restrict access to third-party applications

### ISSUE THREAD

**Issue by tonyganch** [shower/shower#288]
This is an administrative issue.

Currently shower organization allows access to all third-party apps.
It means if any member of org personally grants access to some application, this app will also get access to shower's data.

From GitHub's help page:

> When an organization has not set up third-party application restrictions, any third-party application authorized by an organization member can also access the organization's private resources.

Here are instructions how to fix that: https://help.github.com/articles/enabling-third-party-application-restrictions-for-your-organization/

I'm planning to grant read/write access to third-party app for my personal account and it will affect shower org as well unless fixed.
I'd like to make sure you're aware of that.
Please let me know when I can continue with my thing.

**Comment by pepelsbey** [comment]
Done. Thank you for heads up.
