### ISSUE TITLE
Paragraph inside `<li>`

### ISSUE THREAD

**Issue by rauschma** [shower/shower#293]
```html
<section class="slide">
    <h2>Shower key features</h2>
    <ul>
        <li><p>Built on HTML, CSS and vanilla JavaScript</p></li>
        <li>Works in all modern browsers</li>
        <li>Themes are separated from engine</li>
        <li>Modular and extensible</li>
        <li>Fully keyboard accessible</li>
        <li>Printable to PDF</li>
    </ul>
    <p class="note">Shower ['ʃəuə] noun. A person or thing that shows.</p>
</section>
```

This HTML (note `<p>` inside first `<li>`) looks as follows:

<img width="353" alt="shower-bullet-list" src="https://user-images.githubusercontent.com/526114/28079126-778f53bc-6667-11e7-836f-3a25576714a5.png">

**Comment by pepelsbey** [comment]
It seems [the way I put list bullets](https://github.com/shower/ribbon/blob/master/styles/slide/content/lists.scss#L13) is not universal enough. Will take care of that, thank you.

**Comment by shvaikalesh** [comment]
<details>
  <summary>HTML code</summary>

```html
<section class="slide">
    <h2>Shower key features</h2>
    <ul>
        <li>
            <p>The issue was fixed</p>
            <p>in latest major of Shower themes</p>
            <p>Thanks for reporting</p>
        </li>
        <li>Works in all modern browsers</li>
        <li>Themes are separated from engine</li>
        <li>Modular and extensible</li>
    </ul>
    <p class="note">Shower ['ʃəuə] noun. A person or thing that shows.</p>
</section>
```
</details>

<img width="690" alt="the issue was fixed in latest major of Shower themes. Thanks for reporting" src="https://user-images.githubusercontent.com/5098878/52528349-7c890c00-2ce5-11e9-94cf-f782c3b0e164.png">
