### ISSUE TITLE
Is there a standard way to develop presentation?

### ISSUE THREAD

**Issue by ivstas** [shower/shower#295]
Last time I used shower I created my presentation by adding browsersync and then adding gulp task to watch changed files and instantly see the result in browser.

How do you, contributors of shower, develop your presentation?
I consider submitting a merge request with functionality described above, but probably there is a standard way I missed?
If no, do you consider browser-sync + gulp task suitable to be added to standard presentation template?

**Comment by pepelsbey** [comment]
There’s a [similar task](https://github.com/shower/ribbon/blob/master/gulpfile.js#L13) in Ribbon theme. I thinks it’s a good idea to add something similar to Shower template. Feel free to submit PR! :)

**Comment by pepelsbey** [comment]
Fixed in #296
