### ISSUE TITLE
Text shadows are not printed in Chrome

### ISSUE THREAD

**Issue by morozov** [shower/shower#297]
There's a visual difference between how the slides are displayed on the screen and printed (exported to PDF in Chrome 61). Please see the images below:

### Screen view
![shower-shadows](https://user-images.githubusercontent.com/59683/30825411-bda27f4e-a1e7-11e7-8c84-bf94fd6a0d7e.png)

### Print view
![shower-no-shadows](https://user-images.githubusercontent.com/59683/30825426-d2aed7fc-a1e7-11e7-98a7-3d281769eeef.png)

**Comment by pepelsbey** [comment]
I don’t think there’s anything I can to to fix it. They used to work, they might fix it in the future. I hope I’ll find some time to file an issue, but any printing ussues usually have very low priority.

**Comment by pepelsbey** [comment]
It seems like fixed in Chrome 67

![image](https://user-images.githubusercontent.com/105274/41860180-9e45d600-78a6-11e8-92b4-a0793910488a.png)

**Comment by morozov** [comment]
Works for me too. Thank you.
