### ISSUE TITLE
hide/`display:none` slide when not active in full presentation mode?

### ISSUE THREAD

**Issue by patrickhlauke** [shower/shower#298]
Just wondering if there's a reason why, when presenting, slides are "stacked" rather than using `display:none` to remove all but the `.active` slide. The current behavior, combined with large slide shows with lots of high-res images (which yes, admittedly aren't a fantastic idea for performance) results in heavy image decode thrashing in current Chrome (see https://twitter.com/patrick_h_lauke/status/911962086875521026 and https://bugs.chromium.org/p/chromium/issues/detail?id=768799).

I've patched this in my presentation here, but wondering why that's not default behavior for shower.

https://github.com/patrickhlauke/getting-touchy-presentation/commit/aa9bd6eddbbf7e8645c851b3ce2554ae17aff4de

**Comment by pepelsbey** [comment]
I did it mostly to prepare slides for possible animations. But I never managed to implement it. In fact, I even hate it. So if you say it would make performance better, I’ll try to make it a default behavior.

**Comment by pepelsbey** [comment]
Right, there’s another problem: with `display: none|block` animated special effects like growing and shrinking shouts stop working, see [next 2 sliles](https://shwr.me/shower/themes/ribbon/#23) in fullscreen mode.

Here’s the [code for animation](https://github.com/shower/ribbon/blob/master/styles/slide/elements/shout-full.scss). I’m not exactly sure how to make it work with `display: none`

**Comment by pepelsbey** [comment]
[Here’s the demo](https://codepen.io/pepelsbey/pen/LzQqZv?editors=1100) and it seems that no animation could be triggered on a slide after `display: none` to `block` switch.

**Comment by patrickhlauke** [comment]
wonder if using CSS animation instead of transition could work...

**Comment by patrickhlauke** [comment]
Of course, this makes it more cumbersome, but it seems to work - see demo https://codepen.io/patrickhlauke/pen/veRyyB?editors=1100

**Comment by pepelsbey** [comment]
Yay! Will release Ribbon and Material versions with `display: none` this week. Thank you :)

**Comment by pepelsbey** [comment]
There’s a problem: when something’s `display: none` it doesn’t take part in counters. Meaning, that I can generate slide numbers only in list mode, in full mode every slide will be `1`. Any idea what to use instead of `display: none` to achieve the same perf results?

**Comment by patrickhlauke** [comment]
i've actually switched to `visibility:hidden` ... does that also cause the same counter issue? https://github.com/patrickhlauke/getting-touchy-presentation/commit/7180a69cf038d4275e0aa825c443d0a8d5c688f3

**Comment by patrickhlauke** [comment]
also, the perf problem seems to have been fixed (not yet in stable, but at least in canary), so you *may* get away with not actually fixing anything in the worst case...

**Comment by pepelsbey** [comment]
If you wait long enough _any_ perf problem would go away :D

**Comment by patrickhlauke** [comment]
![Capture from war games: Greetings professor Falken. Hello. A strange game. The only winning move is not to play](https://i.ytimg.com/vi/6DGNZnfKYnU/hqdefault.jpg)

**Comment by pepelsbey** [comment]
There’s a problem with visibility: if you use it for something else (like `class="next"` steps) it will override parent’s visibility and pop-up over the current slide from somewhere else.

**Comment by pepelsbey** [comment]
Good old `clip: rect(0 0 0 0)` to `clip: auto` switching works fine too.
