### ISSUE TITLE
Troubles marking up <blockquote>

### ISSUE THREAD

**Issue by shvaikalesh** [shower/shower#309]
I use `<footer>` in `<blockquote>` element to mark up citation (per [this article](http://html5doctor.com/cite-and-blockquote-reloaded/)).

Sadly, Shower interferes with [this selector](https://github.com/shower/ribbon/blob/4a45b78f4fe2136ae06329e90d1349f78bd00f6b/styles/slide/content/footer.scss#L5), making the `<footer>` completely invisible.

I think we can easily fix this by adding child combinator: `.slide > footer`.

<details>
<summary>My current workaround</summary>

```css
.slide footer { all: unset }
```
</details>

**Comment by pepelsbey** [comment]
Fixed in [material](https://github.com/shower/material/commit/abdff16c065eeff081916e032155a5ef7933ac87) and [ribbon](https://github.com/shower/ribbon/commit/07f4431caf5d6f85f82ef3a206661366dad2be1a) and released.
