### ISSUE TITLE
x-ua-compatible

### ISSUE THREAD

**Issue by Eugeno** [shower/shower#310]
Is `<meta http-equiv="x-ua-compatible" content="ie=edge">` still relevant?
Btw, it's better to place `charset` above `title`, isn't it?

**Comment by pepelsbey** [comment]
It used to help with old IEs, to keep them in standard compatible mode for local files. Haven’t tested this behaviour for while. Will do and remove it if IE11 behaves without `x-ua-compatible`.

Thanks!

As for charset, order doesn’t really matter. Correct server headers for HTML files, that’s what matters.

**Comment by pepelsbey** [comment]
Strangely enough, it still works in IE11, with meta tag:

![image](https://user-images.githubusercontent.com/105274/37519566-9e497042-292a-11e8-8f3f-99dd22774b73.png)

Without, in IE7 mode:

![image](https://user-images.githubusercontent.com/105274/37519591-b909b964-292a-11e8-8929-c817c531da1c.png)

**Comment by Eugeno** [comment]
It seems, that `x-ua-compatible` need only for unsupported IE9-, and no need for IE11. Don't realy know, if someone uses Shower at IE9 =)

> Correct server headers for HTML files, that’s what matters.

That's true, just a safety net.

**Comment by pepelsbey** [comment]
I don’t see any difference in rendering, though. It’s not supposed to work in IE7 mode, so I think there’s something wrong with mode switching.

**Comment by Eugeno** [comment]
https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/dev-guides/bg182625(v=vs.85)#document-mode-changes

> Use the HTML5 document type declaration to enable edge mode

> If you currently use the x-ua-compatible header to target a legacy document mode, it's possible your site won't reflect the best experience available with IE11.

Is it?

**Comment by pepelsbey** [comment]
Yes, it’s seems `<! doctype html>` is enough for IE11 to behave the way I need with local files. Will remove meta tag. Thanks!
