### ISSUE TITLE
How i can create new theme?

### ISSUE THREAD

**Issue by avdeev** [shower/shower#315]
Are there any tutorials, recomendations or guidelines for this?

**Comment by pepelsbey** [comment]
The easiest way to create a theme is to fork Material one, change the main color and then customize everything else you need. There’s an idea to create a blank theme that could be used for the new ones, but it’s just an idea yet.

But you don’t have to follow this path if you want to creat truly original theme. There are only three API points that connect JS to a theme:

1. `shower` with `list` and `full` states
2. `slide` with `active` and `visited` states
3. `progress` with `width` attribute

The rest is up to you.

**Comment by avdeev** [comment]
@pepelsbey Thanks!

1) Why to fork the Material, not Ribon?
2) What about creating a theme generator for the project, like [videojs/generator-videojs-plugin](https://github.com/videojs/generator-videojs-plugin)?

**Comment by pepelsbey** [comment]
Material is a bit more neutral and ready for customization. [There’s one generator](https://github.com/kirjs/generator-shower) already but I don’t think it’s maintained. Personally I don’t like yeoman generators, I’d prefer [a proper cli tool](https://github.com/shower/cli) that you might’ve noticed already.

**Comment by avdeev** [comment]
Awesome :)

Ready to help with the development, if necessary

**Comment by pepelsbey** [comment]
Please follow shower/cli for updates then. Thank you!
