### ISSUE TITLE
Use EditorConfig from HTMLAcademy?

### ISSUE THREAD

**Issue by avdeev** [shower/shower#316]
Can we use spaces instead of tabs? :)

https://github.com/htmlacademy/codeguide/blob/master/.editorconfig

**Comment by pepelsbey** [comment]
I don’t mind switching to spaces instead of tabs, [just like we did for shower/core](https://github.com/shower/core/blob/master/.editorconfig#L4). but not 2 spaces. It’s not a Python or YAML.

**Comment by avdeev** [comment]
@pepelsbey Do you need PR?

**Comment by pepelsbey** [comment]
Sure, let’s do it :) I’d start from themes by copying EC from shower/core.

**Comment by pepelsbey** [comment]
Fixed: it’s 4 spaces in all major repositories. I wouldn’t touch the rest repositories for now, most of them are obsolete.
