### ISSUE TITLE
Images not rendered

### ISSUE THREAD

**Issue by computationalstylistics** [shower/shower#322]
Hi there!

After upgrading R to ver. 3.5.0 and, consequently, the packages `rmarkdown` and `rmdshower`, I cannot render presentations created a few weeks ago. I get the following issue: the code in my source file:

`![title](img/fig_3.png)`

is rendered:

`<p><img data-src="img/fig_5.png" alt="title"/></p>`

rather than

`<p><img src="img/fig_5.png" alt="title"/></p>`

The issue affect the following setup:

* macOS High Sierra 10.13.4
* R version 3.5.0
* rmarkdown_1.9

And it works flawlessly on a linux machine, regardless of the upgrades:

* Debian GNU/Linux 8 (jessie)
* R version 3.3.3
* rmarkdown_1.9

**Comment by pepelsbey** [comment]
This kind of rendering is not related to Shower at all, please file an issue to rmarkdown or rmdshower projects, this is happening on their side.
