### ISSUE TITLE
Add print script for PDF export

### ISSUE THREAD

**Issue by pepelsbey** [shower/shower#326]
Currently, Shower [printing docs](https://github.com/shower/shower/blob/master/docs/printing.md) suggest using Chrome for printing slides, which sometimes could be unreliable for presentations with a large number of slides.

But it’s also possible to print Shower slides to PDF using puppeteer:

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  await page.goto('index.html')
  await page.pdf({ path: 'css-magic.pdf', width: '1024px', height: '576px' })
  await browser.close()
})()
```

It would be great to have a command like `npm run print` that would produce PDF. But I already see a possible problem: it seems puppeteer won’t guess page size based on `@page` rule (just like normal Chrome would), `format` (or `width` and `height`) has to be explicitly specified in `page.pdf` function.

[See docs](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions) for `page.pdf(options)`.

**Comment by avdeev** [comment]
@pepelsbey Why it could be unreliable?

I thing that using a full-fledged (with head :)) browser should be more reliable.

**Comment by pepelsbey** [comment]
Just a few problems:

1. By default print dialog using an actual printer as a target, it should be changed to PDF to make it work. It’s an extra step that confuse many people.
2. If you print from full mode you’ll get your slides distorted because of `transform: scale(x)` applied to `<body>`. It only works as expected from list mode and also quite confusing.
3. Some big presentations take ages to generate PDF preview, sometimes it just crashes. For some reason, Puppeteer is much more reliable.
4. If you’re Edge, Firefox or Safari user… well, you have to open or even install Chrome.

**Comment by stas-dolgachov** [comment]
@pepelsbey I would like to try. I am new to the Shower, so it might take some extra time for me to get familiar with the code base, but still.

**Comment by nikolay-govorov** [comment]
[CLI](https://github.com/shower/cli) can it. If it works the wrong way, or you meet the error, create a issue for CLI – I will correct.

**Comment by pepelsbey** [comment]
It would be good to integrate printing into shower package itself using shower-cli in npm script. @nikolay-govorov, is it something that could be easily done or it would require some changes?

**Comment by pepelsbey** [comment]
OK, it seems it would be better to make it a part of [shower-cli](https://github.com/shower/shower-cli) package and then implement it via npm scripts back here. So please welcome to [cli/issues/6](https://github.com/shower/cli/issues/6) for improving PDF printing.

**Comment by nikolay-govorov** [comment]
@pepelsbey, no, adding print to this repository should be very easy.
