### ISSUE TITLE
The first <pre> on a slide has unwanted margin-top

### ISSUE THREAD

**Issue by mistakster** [shower/shower#329]
I have some slides which contain only blocks of code like the following example.

```
<section class="slide">
    <pre>
        <code>Some text here</code>
    </pre>
</section>
```

I’ve spotted that the text is not aligned correctly. Please, see the examples below.

![Unwanted gap at the top of the block](https://user-images.githubusercontent.com/531671/44616301-b44ee500-a866-11e8-9375-b50c33946723.png)

![The same block without the gap](https://user-images.githubusercontent.com/531671/44616300-b44ee500-a866-11e8-84ca-7ac001dfe274.png)

The fix can be as the following:

```
.slide pre:first-child {
  margin-top: 0;
}
```

@pepelsbey, please, let me know if you think that the fix is relevant and I will make a PR then.

**Comment by pepelsbey** [comment]
Yes please! I guess it’s caused by reset.css removed it the latest major versions of Ribbon and Material. There’s a proper reset for `<p>`, but I [completely forgot](https://github.com/shower/ribbon/blob/master/styles/slide/content/code.css) about `<pre>`’s margins.

```css
.slide p {
    margin-top: 0;
    margin-bottom: 1em;
}
```

**Comment by pepelsbey** [comment]
And while you’re at it, could you please check if there’s anything similar happening with other elements? I’d appreciate it :)

**Comment by mistakster** [comment]
Sure. I’ll make the PR later today. Cheers!

**Comment by mistakster** [comment]
@pepelsbey, I‘ve checked other styled elements. They seem to be fine.
