### ISSUE TITLE
PT Sans Narrow font is not loaded

### ISSUE THREAD

**Issue by vmarkovtsev** [shower/shower#332]
I don't get the font for the headers when I load the presentation page:

![image](https://user-images.githubusercontent.com/2793551/45929930-9d300f80-bf58-11e8-8ca7-428d5e9c4963.png)

Tested on Chrome 59 and Firefox 62 on Linux.
Ctrl-R fixes the fonts.

I tried to include the fonts CSS in the header:

```html
<link rel="stylesheet" href="node_modules/shower-ribbon/styles/fonts.css">
<link rel="stylesheet" href="node_modules/shower-ribbon/styles/styles.css">
```

which helps - now I don't get the font on cold load (Ctrl-Shift-R) only once per 5 tries.

I don't reproduce this with `localhost`. There seems to be a font loading race which is sensitive to the internet speed.

**Comment by pepelsbey** [comment]
Yep, my bad. You can fix it in font.css by changing `font-display` property value (or removing it altogether) from `optional` to `swap`, for example. I’ll fix it as soon as possible. Feel free to send PR to Ribbon and Material :) I’m not sure though what value would be better.

**Comment by vmarkovtsev** [comment]
I will hack on my side and wait for your fix :smile:  Thanks for a :zap: response!

**Comment by vmarkovtsev** [comment]
Fixed
