### ISSUE TITLE
Updated the structure of the publishing packages

### ISSUE THREAD

**Issue by nikolay-govorov** [shower/shower#336]
So that we can conveniently manage dependencies and easily publish new parts of Shower, it would be cool to install packages from a common namespace. For example `@shower/cli` or `@shower/core`

To do this, you need to update the structure of the repository, which is published under the name `shower`. The problem is that this repository now contains a template for creating a new presentation.

Since the CLI will be ready soon and the creation of the presentation from the template will become obsolete, I suggest moving the template to the `shower/template` repository and working on a new structure in the `shower/shower` repository

The only doubt is that if we move the template from the main repository, we can break the usual template. If you also have such doubts, I can offer to add an intermediate step, until we do not prohibit the creation through the template, then we can create a new structure in a separate repository, for example `packages`. There we will take the name on the npn, and when fully move to the new structure – update the root repository.

To do this, follow these steps:
- [ ] Create repository for new structure: for example `packages`
- [ ] Move the first package to the new structure
- [ ] Publish packages from the new structure to NPM
- [ ] After the release of the CLI to migrate the template into repository `template` and `packages` rename to `shower`.

**Comment by avdeev** [comment]
Intermediate step sounds good.

**Comment by pepelsbey** [comment]
I’d prefer `shower/shower` to remain user-faced repository as it’s a default one for issues and historically. If there’s a template presentation, why don’t we keep it here instead of hiding it in `shower/cli` internals and mixing JS code with HTML content in the same repository.

Is it possible for `shower/cli` to use `shower/shower` contents as a sample presentation? There could be not just `shower create` with a single blank slide, but also `shower sample` that would create a sample presentation with pictures and text. I’d love to improve the current sample presentation content to better reflect Shower’s features and auto-deploy it to [shwr.me](https://shwr.me/) as it happening right now, see [shower/shwr.me](https://github.com/shower/shwr.me) repository for details.

**Comment by nikolay-govorov** [comment]
It seems to me that what is in `shower/shower` and what is generated through the CLI are different things. I think the CLI should generate an empty presentation.

In addition, the template from which the CLI generates the presentation is unusable. For example, there in the template is substituted theme and aspect ratio.

I like the idea of keeping the template separate from the tool, but I don't think mixing a technical template and a use case is the best idea

**Comment by pepelsbey** [comment]
> I think the CLI should generate an empty presentation

I totally agree: _by default_ it should generate an empty presentation. But I also suggested sample option, which often exists in tools like this. And we could keep template in the main repository. I don’t want CLI to become the only option for using Shower. Sure, it’s the most convenient one, but it takes some specific knowledge. I want to keep existing `shower.zip` and `git clone shower/shower` options too.

> template from which the CLI generates the presentation is unusable

We can make it usable (using Ribbon and 16:9 default) and then change it in CLI during initialization. Just like we already do with `node_modules` paths replacement.

No, seriously, using `shower/shower` main repository for keeping configs is way too DX-centric. I want it to be user-friendly.

**Comment by nikolay-govorov** [comment]
I agree that the CLI should not be the only way to use Shower. The CLI in this case is not so much a way to create a presentation as a kernel to manage it. Instead of the old gulpfile. Even if the presentation is downloaded as `shower.zip`, **it will still use the CLI**. In other words, in `shower/shower` is not a template, and have already created a presentation.

I like the ability to use my own templates, so I suggest:

- Add capability to the CLI 
- To make the template blank presentation and a presentation with examples in a separate repository.
- In `shower/shower` put generated from template with example presentation.

I really want to store templates in a way that's easy to process – it's very, very easy to work with them, and it allows the user to use their own templates

**Comment by pepelsbey** [comment]
SGTM :)
