### ISSUE TITLE
can't not work with medium-zoom

### ISSUE THREAD

**Issue by wulucxy** [shower/shower#337]
Hi，
  I wanna to some feature like [medium-zoom](https://github.com/francoischalifour/medium-zoom)，but because the project add a lot action on body，I tried a lot，but still failed。
  do you guys have any suggestion?

**Comment by pepelsbey** [comment]
What exactly are you trying to achieve: change Shower’s behavior or use external script?

**Comment by wulucxy** [comment]
hi，@pepelsbey。the case is：

![image](https://user-images.githubusercontent.com/5326403/47994976-eb772780-e12e-11e8-8d6b-4fc245102b7c.png)

when I show the slide on a big hall，the people in the last rows is unable to see the code。

so，I wanna to show the original pic in the center of the screen when I click the small pic。

the problem is root element：body has too much thing，including layout and scale。

so，what I really want is give the purified body without any class。

or，do you have any advice?

**Comment by pepelsbey** [comment]
Unfortunately this is how Shower scaling works. And there’s no way to change it without breaking everything else. But there are plenty of ways to make it work the same way.

If you want your pictures to become bigger, make them bigger. You don’t need a gallery script for that. You can put a picture to the next slide and make it bigger. You can use the `next` class to trigger some changes inside of the current slide. [See how this gallery works](https://shwr.me/shower/themes/ribbon/#36).

But I wouldn’t suggest using pictures for code samples. It makes it inaccessible and harder to read. Use `<pre>`, `<code>` and plain text, really.
