### ISSUE TITLE
Improve contrast-ratio for header

### ISSUE THREAD

**Issue by Semigradsky** [shower/shower#339]
The header on 'ribbon' theme is really hard to read.
It has constrast-ratio - 1.57

![screenshot from 2018-11-27 14-19-11](https://user-images.githubusercontent.com/1198848/49078767-f285e700-f24f-11e8-82c0-2dc5b45d1cff.png)

For example, changing header colour to white (constrast-ratio - 6.83):
![screenshot from 2018-11-27 14-18-56](https://user-images.githubusercontent.com/1198848/49078827-2234ef00-f250-11e8-81b2-e7134d760170.png)

**Comment by pepelsbey** [comment]
You’re totally right, contrast ratio is way to small. I’ll think about it, it’s more than just a “make it brighter” decision, I’d like to keep the same design. Quick test with 3.08 ratio:

![image](https://user-images.githubusercontent.com/105274/49079650-3f6abd00-f252-11e8-9494-13f24070f43e.png)

**Comment by pepelsbey** [comment]
[Fixed](https://github.com/shower/ribbon/commit/774a84601ffa91cb8c9cd7494ed88eed1d1febce) and released. Thank you!

<img width="888" alt="image" src="https://user-images.githubusercontent.com/105274/49120575-40d1cf00-f2be-11e8-8b87-f37dea3b1aaa.png">
