### ISSUE TITLE
Strange working on mobile

### ISSUE THREAD

**Issue by Semigradsky** [shower/shower#340]
How I see presentation (https://shwr.me/) on my device (it is working ok if I turn on full screen in browser):

<details>
<summary>Screenshot 1</summary>

![photo5469740791506250171](https://user-images.githubusercontent.com/1198848/49080027-5827a280-f253-11e8-8c8e-6f060f4f6bd9.jpg)

</details>

<details>
<summary>Screenshot 2</summary>

![photo5469740791506250170](https://user-images.githubusercontent.com/1198848/49080028-58c03900-f253-11e8-8d39-9448b7766bf8.jpg)

</details>

<details>
<summary>Screenshot 3</summary>

![photo5469740791506250169](https://user-images.githubusercontent.com/1198848/49080029-58c03900-f253-11e8-9df4-d247ffb66c8b.jpg)

</details>

<details>
<summary>Screenshot 4</summary>

![photo5469740791506250168](https://user-images.githubusercontent.com/1198848/49080031-58c03900-f253-11e8-8200-91aefd61fd03.jpg)

</details>

**Comment by pepelsbey** [comment]
Unfortunately, Shower is not really optimized for using in full screen mode on mobile.

Version 3.0 refactoring is almost finished and this will be the number one priority once it’s released.

**Comment by Semigradsky** [comment]
Oh, it is working perfect on full screen mode for me:
<details>
<summary>Screenshot 1</summary>

![photo5469740791506250167](https://user-images.githubusercontent.com/1198848/49080750-b35a9480-f255-11e8-9c3a-e1584fb11613.jpg)

</details>
<details>
<summary>Screenshot 2</summary>

![photo5472331086282467851](https://user-images.githubusercontent.com/1198848/49080751-b35a9480-f255-11e8-8316-e5937080f95f.jpg)

</details>

It is working bad for ordinary mode.

**Comment by pepelsbey** [comment]
It’s not a list mode on your first pictures. I wonder if you could list steps to reproduce:

1. Open anonymous tab in Chrome browser on Android
2. Type URL
3. …

I would really help. I’ll also test it on Android later today.
