### ISSUE TITLE
Add an option to disable hotkeys?

### ISSUE THREAD

**Issue by kix** [shower/shower#342]
Currently, `Enter` is always switching to the next slide, while `Shift+Enter` goes to the previous. This makes it impossible to use a `<textarea/>` inside a slide (for example, when embedding [@viebel/klipse)](https://github.com/viebel/klipse). There should be some way to disable the keypress handlers via configuration.

Perhaps this could be achieved by passing the `Shower`'s options to all of the plugins [in `installModules()` here](https://github.com/shower/core/blob/3ad992891d70926054ec285cd2afcf97bb045abf/lib/shower.js#L43)?

**Comment by pepelsbey** [comment]
There supposed to be a special measure for preventing shortcuts to mess with interactive elements, such as links, buttons, inputs, etc.

It’s clearly a bug if it doesn’t work. Could you please provide a demo or code sample?

**Comment by kix** [comment]
Wow, thanks for such a quick reply, @pepelsbey :)
Here's a quick demo: https://elated-hawking-792449.netlify.com
Source: https://github.com/kix/cljs-talk
Could this be related to some magic behind klipse attaching its listeners? Even if so, I think since Shower will never really know what 3rd party scripts are embedded and how they'd handle keypresses, we might need a way to fine-tune the keypress behaviour.

**Comment by kix** [comment]
Hm, although I forgot I've added a simple `<textarea>` on the next slide, and the problem persists there, too.

**Comment by shvaikalesh** [comment]
Shower's approach of [detecting interactive elements](https://github.com/shower/core/blob/master/lib/utils/index.js#L2) should work with most third-party components. Particularly, the ones built with basic accessibility (like, handling focus) in mind.

`klipse` uses hidden `<textarea>` to handle input: `@shower/core` beta detects it correctly and disables hotkeys. It is pretty safe to update: please try it out.

**Comment by kix** [comment]
Thanks! Will test and report here if it's all good

**Comment by kix** [comment]
Resolved in beta
