### ISSUE TITLE
new cloning way

### ISSUE THREAD

**Issue by ishpartko** [shower/shower#347]
Could I add the new way to cloning repo in README.md?

Easy way to clone any project without console:

https://github.com/new/import

I could describe how to use it for our needs in readme

**Comment by ishpartko** [comment]
Maybe we could add it, as additional way for cloning

**Comment by ishpartko** [comment]
https://github.com/shower/shower/issues/345

**Comment by pepelsbey** [comment]
Yeah, sure, go for it :)

**Comment by shvaikalesh** [comment]
Resolved by #348.

New cloning way is totally awesome.
Thank you, @ishpartko.
