### ISSUE TITLE
How to manage multiple presentations?

### ISSUE THREAD

**Issue by sundy-li** [shower/shower#349]
Hi, I use shower to build presentations. But each project repo took too much disk (node_modules mostly), it's there any way to manager multiple presentations in one project?

**Comment by pepelsbey** [comment]
Hi there,

There are two simple ways of starting a Shower presentation:

1. You can download an archive with all needed files: [shwr.me/shower.zip](https://shwr.me/shower.zip) and manage development on your own: save and reload or some local server with live-reload, like [live-server](https://www.npmjs.com/package/live-server).
2. Or you can use shower-cli tool to quickly start presentation in any folder without cloning shower/shower template repository. Once you install it globally `npm i -g shower-cli` there will be `shower` command available. For example, `shower create sample` will ask you a few questions and create an empty presentation in the `sample` directory. There’s `shower serve` for live-reload server, `shower pdf` for exporting PDF, etc.

The second approach will still install dependencies into `node_modules`, around 257 MB. So if you want to save some space, I’d go for the first one.

**Comment by sundy-li** [comment]
Hi， thanks for for reply.
I think the first solution could be more suitable for me.

But I do think maybe the `shower-cli`  could add some options to support `node-modules` directory customization.
Eg.
```
shower create sample --node-module=../base/node-modules
```

It will create a project `sample`, and link the `node-modules` to the `../base/node-modules`.
All the presentations could use the base `node-modules` directories.  257 MB per project is very expensive cost, right?

**Comment by pepelsbey** [comment]
Sounds good, I’d use it myself.

@nikolay-govorov what do you think?

**Comment by sundy-li** [comment]
```
➜  ppt shower create project_b
? Select theme ribbon
? Select presentation ratio 16:9

  ✔ Creating project structure in "project_b" dir
  ✔ Installing dependencies
Project created in project_b dir 🎉 [in 287s]
➜  ppt du -sh project_b
310M	project_b
```

I use shower-cli to create project, it's 310M, my mac only has  128G and I'd like to save many projects  :)

**Comment by kizu** [comment]
Maybe I am missing something, but can't we use multiple .html files for all the presentation in the same one folder? And if CLI doesn't support that yet, it could maybe support creating new html files instead of the whole folder when you're already inside a folder with a shower presentation?

**Comment by pepelsbey** [comment]
Well, you can. But there’s no good system or just an idea for deploying and resource management.

**Comment by nikolay-govorov** [comment]
Hey. I apologize for the long absence.

The main volume is `@shower/cli`. We can add the ability to use globally installed `@shower/cli` from the presentation, and locally put only `theme/core` and the like.

**Comment by nikolay-govorov** [comment]
I figured without a locally installed `@shower/cli` `node_modules` would weigh about 1MB. @pepelsbey, @sundy-li, @kizu what do you think?

**Comment by sundy-li** [comment]
Sounds great, will this feature be released in the future？
