### ISSUE TITLE
Failing npm install or npm ci

### ISSUE THREAD

**Issue by avdeev** [shower/shower#353]
Since NPM 6.12 (https://github.com/npm/cli/releases/tag/v6.12.0) `npm ci` and probably `npm install` runs prepare script for git dependencies. This new behavior calls `prepare` script before the dependencies are installed and causes an error.

```
$ npm install

> shower@2.7.0 prepare /Users/alexeyavdeev/projects/shower
> shower prepare --files '**' --files '!{docs,node_modules,prepared}{,/**}' --files '!*.{md,toml,json}'

Error: File not found with singular glob: /Users/alexeyavdeev/projects/shower/node_modules/@shower/core/shower.min.js (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/Users/alexeyavdeev/projects/shower/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:313:26)
    at Glob.emit (events.js:223:5)
    at Glob._finish (/Users/alexeyavdeev/projects/shower/node_modules/glob/glob.js:197:8)
    at done (/Users/alexeyavdeev/projects/shower/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/Users/alexeyavdeev/projects/shower/node_modules/glob/glob.js:688:12)
    at /Users/alexeyavdeev/projects/shower/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/Users/alexeyavdeev/projects/shower/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/Users/alexeyavdeev/projects/shower/node_modules/glob/glob.js:764:12)
    at RES (/Users/alexeyavdeev/projects/shower/node_modules/inflight/inflight.js:31:16)
```

I suggest renaming `prepare` in  to something different. For example, we can use `build`.

Now, we need to use `npm install --ignore-scripts` to successfully install dependencies.

**Comment by pepelsbey** [comment]
I have the following versions of Node and npm and I don’t see any problems with the name of the script:

```
$ node -v
v13.7.0
~
$ npm -v
6.13.6
```

> Now npm ci runs prepare scripts for git dependencies

I don’t think it means `npm run prepare`, it’s just a word, not the script name. Is it?

**Comment by avdeev** [comment]
@pepelsbey The NPM documentation says this is the default script name.

https://docs.npmjs.com/misc/scripts
> prepare: Run both BEFORE the package is packed and published, on local npm install without any arguments, and when installing git dependencies (See below). This is run AFTER prepublish, but BEFORE prepublishOnly.

Maybe this is my mistake. I'll investigate. But renaming `prepare` to `build` fixed my error.

**Comment by pepelsbey** [comment]
I don’t mind renaming script to build, it would be the safe option. I’ll prepare PR and will ask you for review :)

**Comment by pashkes** [comment]
I have the same error with node.js v14.5.0
I used nvm to toggle node.js v13.7.0

**Comment by pepelsbey** [comment]
I tried it with Node v14.7.0 and it worked fine. Could you please test it again? I might be doing it wrong.

```
~/Projects/Shower/shower on master
$ node -v
v14.7.0
~/Projects/Shower/shower on master
$ npm -v
6.14.7
~/Projects/Shower/shower on master
$ npm install

> @shower/shower@3.0.0 prepare /Users/pepelsbey/Projects/Shower/shower
> shower prepare --files '**' --files '!{docs,node_modules,prepared}{,/**}' --files '!*.{md,toml,json}'

  ✔ Project preparation in progress
Project prepared in prepared dir 🎉
audited 646 packages in 3.284s

19 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

~/Projects/Shower/shower on master
$ npm run prepare

> @shower/shower@3.0.0 prepare /Users/pepelsbey/Projects/Shower/shower
> shower prepare --files '**' --files '!{docs,node_modules,prepared}{,/**}' --files '!*.{md,toml,json}'

  ✔ Project preparation in progress
Project prepared in prepared dir 🎉
```

**Comment by pepelsbey** [comment]
I sat down to fix it, but first I tried to reproduce it. The reason I’m hesitant because the “prepare” word is also used in [@shower/cli](https://github.com/shower/cli) package and it will require both packages to change API and naming. I’ll do this if there’s no other way, I just want to make sure that it’s inevitable.

**Comment by avdeev** [comment]
@pepelsbey I think you already have a node_modules folder.

Try to:
```sh
rm -rf node_modules
npm install
```

or

```sh
git clone ...
npm install
```

**Comment by pepelsbey** [comment]
@avdeev it worked fine

```
~/Desktop
$ node -v
v14.7.0
~/Desktop
$ npm -v
6.14.7
~/Desktop
$ git clone git@github.com:shower/shower.git
Cloning into 'shower'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 2923 (delta 0), reused 1 (delta 0), pack-reused 2920
Receiving objects: 100% (2923/2923), 14.64 MiB | 7.88 MiB/s, done.
Resolving deltas: 100% (1489/1489), done.
~/Desktop
$ cd shower/
~/Desktop/shower on master
$ npm i

> @shower/shower@3.0.0 prepare /Users/pepelsbey/Desktop/shower
> shower prepare --files '**' --files '!{docs,node_modules,prepared}{,/**}' --files '!*.{md,toml,json}'

  ✔ Project preparation in progress
Project prepared in prepared dir 🎉
added 646 packages from 402 contributors and audited 646 packages in 7.503s

19 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by avdeev** [comment]
@pepelsbey Now I can't reproduce it either :)

I think you can close the issue

**Comment by pepelsbey** [comment]
Let’s wait for @pashkes’s confirmation, just in case :)

**Comment by pashkes** [comment]
@pepelsbey thanks,` npm i` successfully 
<details><summary>Log</summary>
<p>
`➜  slides npm i

> undefined prepare /Users/pashkes/Desktop/test-shower/slides
> shower prepare

  ✔ Project preparation in progress
Project prepared in prepared dir 🎉
npm WARN slides No description
npm WARN slides No repository field.
npm WARN slides No license field.

up to date in 18.328s

19 packages are looking for funding
  run `npm fund` for details

➜  slides node -v
v14.5.0`
</p>
</details>

**Comment by pepelsbey** [comment]
Thank you for reporting this :) I’m glad it got somehow resolved without API changes.
