### ISSUE TITLE
Is it possible to zoom in/out the plates when navigating

### ISSUE THREAD

**Issue by alex-mironov** [shower/shower#355]
If I use this library, is there a possibility to animate the plates on navigation like this https://work.co/?

**Comment by pepelsbey** [comment]
Sorry for the late reply. Currently it’s not built-in. But you can change the styles for the navigation between slides in presentation mode, [see example](https://github.com/shower/ribbon/blob/master/styles/slide/slide-full.css) from the Ribbon theme.
