### ISSUE TITLE
Add option to disable history state change on modechange

### ISSUE THREAD

**Issue by csarven** [shower/shower#356]
re https://github.com/shower/core/commit/3ad992891d70926054ec285cd2afcf97bb045abf#diff-59f7cf43ae51544e76abf1aa614bd810R5

On enterFullScreen, history state is updated to include "?full" in the URL. This application state need not be exposed as it creates the affordance to share such link. In other words, it ties the URL to the application (JavaScript) and it has no particular use otherwise.

There is past discussion in and around this so I'll just refer to https://github.com/shower/core/pull/109 .

I'd like to be able to use an option - that can be used after initialising shower and before start() - to disable updating history state for the view (full or list). Everything else can remain the same ie. changing the slide would still update the history to include its identifier.

Here is one use where this matters:

* https://csarven.ca/presentations/linked-research-decentralised-web#doctoral-colloquium is a slide;
* that embeds an annotation: https://linkedresearch.org/annotation/csarven.ca/presentations/linked-research-decentralised-web/5ae73ba4-39ee-424f-9459-10e15a6fb534 ;
* where the target of the annotation is the slide.

Under normal circumstances, the annotation is created while in full screen mode, and so the target of the annotation (ie. the slide) would be the URL with ?full ie. https://csarven.ca/presentations/linked-research-decentralised-web?full#doctoral-colloquium . I had to actually manually change the target of the annotation after I've created because otherwise it wouldn't show up - different targets.

So, as I see it, Shower shouldn't "mint" URLs that could potentially be used. Having an option to disable it would be a way out and will make it at least backwards-compatible with v2.

**Comment by pepelsbey** [comment]
I though you have a number of options here, which is rather a good thing, right?

- `/my-slides/` — list mode, no slides selected
- `/my-slides/#10` — `#10` slide selected in list mode
- `/my-slides/?full#10` — `#10` slide selected in full mode

By changing the state of your slides you’re choosing how exactly you want it to be opened. So if you’re on `#10` slide in full mode and want to share it in list mode, you can exit full mode and copy the link or vice versa.

If JS is disabled any link would end up in the list mode even with `?full#10`.

I’m not a big fan of options, I prefer smart defaults that would fit the most of use cases.

**Comment by csarven** [comment]
I've shared a use case that goes beyond the transnational read-first (only?) approach to using slides. It showcases how write can work ie. how another application can create, edit, and annotate slides from the Web browser. That interactivity is arguably best realised in fullscreen mode. However, Shower imposes its view in the URL (while in full mode) on all other applications that may be sharing the DOM and the URL space. If Shower didn't impose, multiple applications can share the same space - so to speak. As it stands, "?full" is not particularly useful to have dangling around when we are talking about data and linking data. The URL with ?full can be used in an ephemeral way ie. when the slideshow is activated and encounters ?full, it can trigger full mode, but then it should remove itself from the history.

Having options entails that Shower can be used alongside other applications on the same data without conflicting with the others' operations. If Shower's design intention is to hog or impose a particular history, that should be more clear in the documentation.

I'm open to other options as to how this can be accomplished. I suppose there is always the option for other applications to undo or clean-up what Shower leaves behind.

IMO:

>/my-slides/ — list mode, no slides selected

Agree. Slideshow URL only including path ie. without query or fragments should be the list mode

>/my-slides/#10 — #10 slide selected in list mode

Disagree. Enable full mode. List mode if JavaScript is disabled.

>/my-slides/?full#10 — #10 slide selected in full mode

Not required.

**Comment by pepelsbey** [comment]
> > `/my-slides/#10` — `#10` slide selected in list mode
>
> Disagree. Enable full mode. List mode if JavaScript is disabled.

Right, now I see where you’re coming from. You want Shower to default in full mode instead of list. There’s a way to do this:

```
<body class="shower full">
<body class="shower list">
```

By changing the root class name in your HTML you can set the default mode. Does this `?full` parameter bothers you less now?

**Comment by csarven** [comment]
No because ?full still exists. Loading /#10 updates history to /?full#10.

**Comment by pepelsbey** [comment]
Loading `#10` won’t update your URL to `?full#10` unless you have `<body class="shower full">` in your HTML. But if you’ll go to full mode then the `?full#10` will appear indicating the mode you’re in.

I’m currently leaning toward decision to keep this feature as is and release shower-core 3 with it. But once I get more feedback from the users I’ll see if it’s worth adding an option.

Meanwhile you can keep using shower-core 2, feature-wise it’s almost the same. Thank you for your feedback!

**Comment by RubenVerborgh** [comment]
Any way to make it pluggable?

**Comment by pepelsbey** [comment]
@RubenVerborgh, do you mean “move it into a default plugin” (so it would be possible to disable) or “make a plugin that could disable it”?

**Comment by RubenVerborgh** [comment]
Separate the URL parsing and generation stuff into a default plugin, so you can override it with another plugin. (Disabling wouldn't be an option.)

**Comment by csarven** [comment]
>Loading `#10` won’t update your URL to `?full#10` unless you have `<body class="shower full">` in your HTML.

Right. That's what you've suggested earlier.. and asked whether that bothered me less. I'm just saying that it didn't change the primary "issue" for me because ?full sticks regardless of the default set in HTML or what's activated by default (if not found ie. list).

I have no strong preference on the possibility of how this can be essentially disabled as long as it is possible.. but I hthink options would be the simplest (as part of its core).. just as there are other options that can be set eg. selectors (or classes) for the key parts of the slideshow.
