### ISSUE TITLE
Please add navigate mouse.

### ISSUE THREAD

**Issue by korenevskiy** [shower/shower#357]
Will there be support for mouse control?
The presentation is managed by the speaker, excellent.
But then this presentation is opened on the site by a normal user, this user can only control either the mouse or gestures.

**Comment by pepelsbey** [comment]
Why do you think that keyboard navigation is not enough? “Normal” user would probably go through slides in list mode by scrolling. As for the speakers, they can also use clickers to navigate.

**Comment by korenevskiy** [comment]
We can talk as much as we want about the need to initially develop a site for mobile phones.
However, Shower only works on a PC and only with the keyboard.
Please see how the [fancybox](http://fancyapps.com/fancybox/3/) js module for images works.
. It can be swiped to move, it can be moved with the mouse, it can be increased, and so on.
Imagine how Sberbank bought 1000 liquid crystal panels in Russia. And launched 1000 presentations on them. The presentation must have an auto mode in which it performs the function of a photo frame on the wall.
Please test fancybox
1. on your mobile phone,
2. Test it on your PC by scrolling the mouse wheel
3. Test it on PC swipes with the mouse.
4. Test it in other modes.

**Comment by pepelsbey** [comment]
Shower is not a slideshow tool (like Fancybox, Fotorama, etc.), though there’s a way to [put a timer on a slide](https://github.com/shower/ribbon/blob/master/index.html#L619-L621). It’s a slide deck and made for presentations. So it meant to be used mostly by speakers on a stage with a clicker in their hands or a keyboard withing a reach (see [a number of shortcuts](https://github.com/shower/shower/blob/master/docs/shortcuts.md) you can use or [specific clicker instructions](https://github.com/shower/shower/blob/master/docs/logitech.md)). It’s also works as a slide deck that can be published online and read mostly in list mode.

All the other ways to interact with slides via mouse, scroll wheel, etc. are not implemented as it would make a terrible UI for the main use case. Though you can make a plugin to make it work this way. You can see how built-in plugins work by [exploring their source code](https://github.com/shower/core/tree/master/lib/modules). Unfortunately there’s no proper docs for them yet.

**Comment by korenevskiy** [comment]
This plugin can do much more. But alas, it has a narrow purpose. Most likely in half a year people will create a fork of it. And continue to adapt to any screens and manipulators.
At the moment, this module cannot be installed, for example, on your site, on the site of clients, on the site in any CMS so that any teacher, schoolchild, student, or coach can use it. Without a high level of input to the technology, this plugin is useless. Since most are able to use it when everything is built into the CMS (Joomla, Drupal, Wordpress)..
P S many compare Windows and Linux, and say that they say the picture on the desktop is more beautiful, the buttons on the Explorer are also better in Linux. But if you take a step to the side, then in Linux you need to already know the terminal otherwise you will be shot. The same is Your plugin, it is like Linux for most. And all you need to add a couple of arrows and a cross. Which can be hidden during the presentation.

**Comment by pepelsbey** [comment]
This project is more that 10 years old and it’s still serving its purpose.

Thank you for making your point, though.

**Comment by Vallek** [comment]
In case anyone is still interested I made a mouse navigation version for myself https://github.com/Vallek/shower
