### ISSUE TITLE
Is this compatible with pandoc?

### ISSUE THREAD

**Issue by ekiim** [shower/shower#365]
I'm currently doing my document writing with pandoc, and I'm trying to implement this as template, for my presentations,
The problem is that I don't find a decent way to build nicely presentations with this template and pandoc. 

I would like to know if there is a way to make this compatible with reveal.js, because if there is, then integrating with pandoc should be a simple, just a matter of changing the selected template.

**Comment by pepelsbey** [comment]
I not familiar enough with Pandoc to be 100% sure, but I still think that it’s rather not compatible. The idea behind Shower is that you write an actual HTML and spice it up with custom CSS. Markdown (or something similar) might work only for simple use cases when you have just heading, lists, paragraphs, etc. But there’s no simple way of adding classed to use built-in primitives.
