### ISSUE TITLE
Ribbon theme. Name of the colors

### ISSUE THREAD

**Issue by AntonShevchuk** [shower/shower#367]
Hi, I use the Ribbon theme, and I want to customize some colors. But when I changed colors, I saw the code of the result looks terrible

```
.shower {
    --slide-ratio: calc(16 / 9);
    --color-blue: red;
    --color-red: lightblue;
    --color-grey: white;
}
```

Yep, it's not a problem, but looks bad.

**Comment by pepelsbey** [comment]
Ribbon theme is not exactly designed to be highly customizable, unlike Material one. You can slightly adjust colors via custom properties, but in most cases you'd need to use CSS to customize it deeper.

Maybe is just how things are with Ribbon, maybe it's an opportunity for the future versions. I'm not sure.

BTW, it's always a good idea to add screenshots to your issues, especially when it's a visual thing.

**Comment by AntonShevchuk** [comment]
It's not a visual problem. It's the issue about code style and variables names. Sorry if I wrongly described "the problem" :)

**Comment by pepelsbey** [comment]
Oh, sorry. I didn’t get it right. It’s a valid concern, but the answer stays the same:

> Ribbon theme is not exactly designed to be highly customizable, unlike Material one.

In Material there’s a `--key-color` that can be used with any color. I might consider using a bit more functional names in the future versions, but I don’t think it’s the right theme for customization, really. I’d rather create a new one, with customization built-in from the start.
