### ISSUE TITLE
Hide cursor after 5 seconds of non-movement for a presentation mode

### ISSUE THREAD

**Issue by neesoglasnaja** [shower/shower#377]
Just the idea that will help avoid extra actions while presenting. A lot of speakers will appreciate this feature 🤩

**Comment by pepelsbey** [comment]
That’s a really nice idea! How I see the implementation:

1. There’s a timer counting down 5s that resets every time mouse moves
2. Once it reaches 0s it adds a class name to the shower root
3. In the theme there’s `cursor: none` attached with this class name
4. Once mouse is moved the class name should be removed

Or something more optimal in terms of performance, but I’d keep the class name. It’d help to keep the logic and presentation separate.
