### ISSUE TITLE
Calculations for shower body can be simplifed

### ISSUE THREAD

**Issue by zoxon** [shower/shower#380]
```diff
.shower.full {
    position: absolute;
    top: 50%;
    left: 50%;
    overflow: hidden;
-   margin-top: calc( var(--slide-height) / 2 * -1 );
-   margin-left: calc( var(--slide-width) / 2 * -1 );
    width: var(--slide-width);
    height: var(--slide-height);
    background-color: black;
-   transform: scale(var(--shower-full-scale)); 
+   transform: translate(-50%, -50%) scale(var(--shower-full-scale));
}
```

![image](https://user-images.githubusercontent.com/3866196/143853118-d37ed35a-0386-4b01-a6dd-17000b7da816.png)

**Comment by pepelsbey** [comment]
Hey! Thank you for the suggestion. I don’t see any dramatic difference in code complexity. Do you have any other idea how this could be better?

**Comment by zoxon** [comment]
Thank you for quick response.
Right, nothing critical here, but from my point of view `transform: translate(-50%, -50%)` describes what we really want to do instead of using magic numbers like 2 or -1.
The choice is yours. Just a suggestion

**Comment by pepelsbey** [comment]
I wouldn’t call 2 and -1 too magical.

I mean, `/ 2` means “half of it” and `* - 1` is a typical way of getting negative number in `calc()`.

Thank you for spotting it anyway!
