### ISSUE TITLE
npm run bundled works incorrect with self-closed tag <link .../>

### ISSUE THREAD

**Issue by avdeev** [shower/shower#384]
`npm run bundled`
works incorrect with self-closed tag link
`<link rel="stylesheet" href="node_modules/@shower/ribbon/styles/styles.css" />`

**Comment by pepelsbey** [comment]
Hey, thanks! Incorrect how exactly? 🙂 Screens, logs, etc. would be useful here.

**Comment by pepelsbey** [comment]
Got it! The source of the problem is in [shower/cli’s regexes](https://github.com/shower/cli/blob/master/core/lib/presentation.js#L27-L34). Feel free to send PR with a fix. Otherwise, I’ll get take care of it a bit later.
