### ISSUE TITLE
slide content height

### ISSUE THREAD

**Issue by mfrigerio17** [shower/shower#385]
Hi,
I noticed that the height of the content of a slide is not capped to the slide's height itself.
See this example, where I explicitly set the height of the div to 100% to demonstrate the problem.
![screenshot](https://user-images.githubusercontent.com/3646506/201873867-90d33df5-51a4-4c45-9350-3c1e149c8844.png)

This is particularly annoying if I insert e.g. an image, as setting its max-height to 100% would _not_ fit it to the slide.

Disclaimer: I am not an HTML CSS expert.
I would expect the max-size of any element inside a `<section class="slide">` to be automatically adjusted to fit the container. (If any content overflows (e.g. a long bullet list), it should be dealt with the overflow rules in css - e.g. display a scroll bar, or hide it completely)

Am I missing something? Thanks

**Comment by pepelsbey** [comment]
Hello! Yes, you're missing the way height: 100% works in CSS. 100% means the full height of the parent, not just available space. It means that it sticks out of the slide exactly by the height of the title.

I'd suggest looking a the examples in the [theme's index file](https://shwr.me/shower/themes/ribbon/): cover and place primitives.

It's easier to style images in fixed units, keeping in mind that the slide's height is 1024 by 576.

**Comment by mfrigerio17** [comment]
aaah.. yes, actually I remember having realized before, in the past, that the amount it sticks out is exactly the height of the title..

> 100% means the full height of the parent, not just available space.

Yes, in fact I did mention that I expected the element to stretch to fit the container (or "parent").
The problem is that the container is just the slide, and not the slide "minus" the title... (stupid me)

The only solution that seems to do what I want, is a flex container:

CSS
```
.title-content {
	  height: 100%;
	  display: flex;
	  flex-direction: column;
}
.title-content > div {
	  flex: auto;
}
```

HTML
```
    <section class="slide">
      <div class="title-content">
        <h2>Title 2</h2>
        <div>
          This div will fill the available vertical space
        </div>
      </div>
    </section>
```
Anything deeply wrong with this?


> It's easier to style images in fixed units, keeping in mind that the slide's height is 1024 by 576.

yes, it is easier, but I was aiming to avoid hardcoded sizes for more flexibility.

Thanks for the fast reply!
