### ISSUE TITLE
Callback for slide and mode changes

### ISSUE THREAD

**Issue by ai** [shower/shower#77]
It will be good to allow external JS know that Shower change slide or open list mode. For example:

``` js
Shower.onFullSlide(function (slide) {
    if ( slide.classList.contains('use3d') ) {
        document.body.classList.add('enabled3d');
    } else {
        document.body.classList.remove('enabled3d');
    }
});

Shower.onList(function () {
    document.body.classList.add('enabled3d');
});
```

I don’t create pul request, because it’s API question. If you agree with this API, I will patch Shower.

Now I need to use `onpopstate`, `onhashchange` and override `pushState` and `replaceState`.

Second question is about jQuery. Why are you don’t use it? :) I ask, because it have very useful `jQuery.Callbacks`.

**Comment by handcoding** [comment]
For @miripiruni and others—do you by chance know of any documentation or examples for this feature? If it may be possible, I’d like to trigger a callback function in some external JavaScript when moving to the next slide.

**Comment by pepelsbey** [comment]
@handcoding, unfortunately, there's no API docs available at the moment, but you can check Shower's [core files](https://github.com/shower/core/blob/master/lib/shower/shower.Player.js) to figure out what events to listen. AFAIK it should be possible. Author of the current API is @zloylos, but I think he's not available.

**Comment by handcoding** [comment]
@pepelsbey @zloylos I’m not new to JavaScript, but I messed with this for an hour and a half, and I couldn’t even get a “hello world” to fire when the next slide appeared.

If either of you might be able to share a quick code example that logs “hello world” to the console when the next slide appears, I’d be super grateful. I don’t mind paying you for your time.

**Comment by pepelsbey** [comment]
@handcoding, there’s [shower/notes](https://github.com/shower/notes) plugin for Shower adding notes to console on every slide switch. It might give you an idea how to use this API or white your own plugin.
